name: Pull Request Merge

on:
  push:
    branches:
      - main

jobs:
  semantic_release:
    runs-on: ubuntu-latest

    container:
      image: node:18

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Yarn Dependencies
      run: |
        yarn install

    - name: Run Semantic Release
      env: 
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }} 
      run: |
        yarn semantic-release --branch=main