name: Build & Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: golang:1.21.5-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Protoc
        run: apt update && apt install -y protobuf-compiler
      - name: Install protoc-gen-salesforce-apex
        run: go install -buildvcs=false ./cmd/...
      - name: Run Tests
        run: go test ./test
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn install
      - name: Show remote URL
        run: git remote -v
      - name: Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          yarn semantic-release --branch=main