name: Pull Request Merge

on:
  merge:
    branches:
      - main

jobs:
  semantic_release_dryrun:
    runs-on: ubuntu-latest

    container:
      image: node:18

    steps:
    - uses: actions/checkout@v2
    - name: Install Yarn Dependencies
      run: |
        yarn install

    - name: Run Semantic Release in Dry-run
      run: |
        yarn semantic-release --branch=main