name: Validate & Test
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: golang:1.21.5-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release
        run: |
          go version