name: Validate & Test
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: ghcr.io/dclappert/protoc-gen-salesforce-apex-runner-container:1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Tests
        run: yarn test